# Generated by Django 4.2.16 on 2026-06-15 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        ('shops', '0001_initial'),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrecord',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_records', to='sales.customer'),
        ),
        migrations.AddField(
            model_name='deliveryrecord',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Linked once the order for this delivery is created.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_records', to='sales.order'),
        ),
        migrations.AddField(
            model_name='deliveryrecord',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_records', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='deliveryrecord',
            name='transporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_records', to='delivery.transporter'),
        ),
        migrations.AddIndex(
            model_name='deliveryrecord',
            index=models.Index(fields=['shop', 'delivery_date'], name='delivery_de_shop_id_0f1947_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deliveryrecord',
            unique_together={('shop', 'customer', 'delivery_date')},
        ),
    ]
