# Generated by Django 4.2.16 on 2026-06-15 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('is_walk_in', models.BooleanField(default=False)),
                ('bottle_tracking', models.BooleanField(default=False, help_text='If true, bottles given to this customer are tracked and must be collected back.')),
                ('bottles_out', models.IntegerField(default=0)),
                ('payment_schedule', models.CharField(choices=[('CASH', 'Cash (pay on delivery)'), ('WEEKLY', 'Weekly credit'), ('MONTHLY', 'Monthly credit')], default='CASH', max_length=20)),
                ('debt_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('delivery_frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKDAYS', 'Weekdays only'), ('CUSTOM', 'Custom days'), ('NONE', 'No standing delivery')], default='NONE', max_length=20)),
                ('delivery_days', models.CharField(blank=True, help_text='Comma-separated weekday numbers (0=Mon..6=Sun) for CUSTOM frequency.', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='shops.shop')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_walk_in', models.BooleanField(default=False)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_status', models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid'), ('CANCELLED', 'Cancelled')], default='UNPAID', max_length=20)),
                ('paper_bags_used', models.IntegerField(default=0)),
                ('bottles_given', models.IntegerField(default=0, help_text='Bottles handed out with this order.')),
                ('bottles_collected', models.IntegerField(default=0, help_text='Empty bottles collected back from the customer.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='sales.customer')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shops.shop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('milk_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.milktype')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.order')),
                ('pack_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.packsize')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('MPESA', 'M-Pesa'), ('BANK', 'Bank'), ('OTHER', 'Other')], default='CASH', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.customer')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_payments', to='shops.shop')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='StandingOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standing_items', to='sales.customer')),
                ('milk_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.milktype')),
                ('pack_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.packsize')),
            ],
            options={
                'unique_together': {('customer', 'milk_type', 'pack_size')},
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['shop', 'created_at'], name='sales_order_shop_id_46fe37_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['shop', 'payment_status'], name='sales_order_shop_id_73f85c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'created_at'], name='sales_order_custome_119c79_idx'),
        ),
        migrations.AddIndex(
            model_name='customerpayment',
            index=models.Index(fields=['shop', 'customer', 'paid_at'], name='sales_custo_shop_id_7d7b06_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['shop', 'is_active'], name='sales_custo_shop_id_10f1f8_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['shop', 'delivery_frequency'], name='sales_custo_shop_id_f0a122_idx'),
        ),
    ]
