# Generated by Django 4.2.16 on 2026-06-15 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shop',
            field=models.ForeignKey(blank=True, help_text='Null for SUPER_ADMIN. Required for OWNER/EMPLOYEE.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['shop', 'role'], name='accounts_us_shop_id_7eab8e_idx'),
        ),
    ]
