# Generated by Django 4.2.16 on 2026-06-15 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('MILK', 'Milk'), ('BOTTLE', 'Bottles'), ('PAPER', 'Paper bags'), ('OTHER', 'Other')], max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='shops.shop')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('MILK', 'Milk'), ('BOTTLE', 'Bottles'), ('PAPER', 'Paper bags'), ('OTHER', 'Other')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('milk_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.milktype')),
                ('pack_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.packsize')),
                ('paper_bag_stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.paperbagstock')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_deliveries', to='shops.shop')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['-delivered_at'],
                'indexes': [models.Index(fields=['shop', 'kind', 'delivered_at'], name='suppliers_s_shop_id_4c17e3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['shop', 'category'], name='suppliers_s_shop_id_cb54b0_idx'),
        ),
    ]
