# Generated by Django 4.2.16 on 2026-06-15 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('sales', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_prices', to='sales.customer'),
        ),
        migrations.AddField(
            model_name='customerprice',
            name='milk_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.milktype'),
        ),
        migrations.AddField(
            model_name='customerprice',
            name='pack_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.packsize'),
        ),
        migrations.AddField(
            model_name='customerprice',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_prices', to='shops.shop'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('shop', 'milk_type', 'pack_size')},
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['shop', 'milk_type', 'pack_size', 'is_current'], name='inventory_p_shop_id_e07cdc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paperbagstock',
            unique_together={('shop', 'label')},
        ),
        migrations.AlterUniqueTogether(
            name='packsize',
            unique_together={('shop', 'label')},
        ),
        migrations.AlterUniqueTogether(
            name='milktype',
            unique_together={('shop', 'name')},
        ),
        migrations.AddIndex(
            model_name='customerprice',
            index=models.Index(fields=['shop', 'customer', 'milk_type', 'pack_size', 'is_current'], name='inventory_c_shop_id_eae414_idx'),
        ),
    ]
